---
version: 2
plan:
  project-key: AJL
  key: DIFFBUILDERBUILD
  name: diff builder - build
variables:
  dockerNode: adguard/node-ssh:22.14--0

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -laht

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            pnpm install ${bamboo_varsPnpm}

            pnpm lint
            pnpm test

            pnpm build

            pnpm pack --out diff-builder.tgz
    - inject-variables:
        file: build.txt
        scope: RESULT
        namespace: inject
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
        configuration:
          selectedRepository: defaultRepository
          tagName: v${bamboo.inject.version}
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -laht

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules
            echo "Size after cleanup:" && du -h | tail -n 1
  artifacts:
    - name: diff-builder.tgz
      pattern: diff-builder.tgz
      shared: true
      required: true
  requirements:
    - adg-docker: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: true

labels: []

other:
  concurrent-build-plugin: system-default
