---
version: 2
plan:
  project-key: AJL
  key: DIFFBUILDERTESTS
  name: diff builder - tests
variables:
  dockerNode: adguard/node-ssh:22.17--0

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -laht

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            # Test diff version
            diff --version

            pnpm install ${bamboo_varsPnpm}

            pnpm lint
            pnpm test
            pnpm test:smoke
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh"
  requirements:
    - adg-docker: true

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
